### ISSUE TITLE
Unable to content negotiate for schema 3.x dois

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#1024]
Unable to content negotiate for schema 3.x dois returns blank.

Examples from user:

DataCite Schema 3.x gives empty results:
curl -LH "Accept:  application/x-bibtex" https://doi.org/10.14470/z6115722
curl -LH "Accept:  application/x-bibtex" https://doi.org/10.14470/ua114590
curl -LH "Accept:  application/x-bibtex" https://doi.org/10.14470/TR560404

This probably is an issue in bolognese, but is reproducible through general content negotiation.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nrkl)

**Comment by kjgarza** [comment]
i think this problem is present in all DOIs with schema different to kernel-4.

this line https://github.com/datacite/bolognese/blob/4317168/lib/bolognese/datacite_utils.rb#L7 is making that metadata to validate is always kernel-4 while the xml files are not.

unless we asked to update to kernel-4 we need to find a way to fix it

https://github.com/datacite/bolognese/blob/4317168/lib/bolognese/writers/datacite_writer.rb#L8 should_passthru is always FALSE, so it ask to create metadata with schema kernel-4

**Comment by kjgarza** [comment]
related https://app.frontapp.com/open/msg_ebin1p1
