### ISSUE TITLE
Internal Feedback - pidservices.org

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#1048]
This issue is to collate internal feedback regarding https://pidservices.org
Please consider the scope of any feedback, ideally limiting to copy or minor style changes.

Website: https://www.pidservices.org

Feedback requested:
* Styling - Please note some styling is intentionally attempting to match other FREYA work.
* Text/Copy - Wording/Spelling/Grammar or additional information
* Data visible - If you think there is critical data missing for the pidservices
* Bugs - Noticeable functionality bugs.
* Other - General comments.

Todo based on feedback:

- [x] About copy changes
- [x] Filter labels should be Title case (use title instead of id)
- [x] Consider naming of "General info"
- [x] for "Scientific Field" label, strip "FOS:"
- [x] logos in footer broken on individual service page
- [x] make sure filters can be reset even if no query results
- [x]  include reset button in search box
- [x] fix pagination

**Comment by mjbuys** [comment]
Text/copy - change about page text “An important thing to realise here is that all services are registered under the repository "datacite.services", without this it will return all services registered regardless if they are related to PID Services.” to something along the lines “All services DOIs are registered under the repository "datacite.services" so that only services associated with https://www.pidservices.org/ are returned."

**Comment by mfenner** [comment]
* Filter labels should be Title case (use title instead of id)
* add styling and change to proper label for `Num services: 14`
* consider moving "Welcome to the PID Services registry." block out of the header. And don't center text.
* use a label that includes "PID" instead of "General info"
* for "Scientific Field" label, strip "FOS:"
* logos in footer broken on individual service page

**Comment by mfenner** [comment]
We need documentation in DataCite support unless we have this already.

**Comment by kjgarza** [comment]
LGTM. Small comments:

- Maybe this is a design decision but I would think that COPY DOI should copy the DOI url, not only the DOI name.
- The Collapsable Accordion  component for the filter, its a bit confusing when you select a type that only one service has (e..g repository) because it hides everything else. I found myself clicking <- (back) more than one time, when in reality i just needed to click unselect

**Comment by richardhallett** [comment]
@mfenner Thanks, can you clarify

1. Not sure what you mean by proper label here, what styling would you like for the "Num services : x" ?
2. General info is general though, e.g. it will show language and TRL if it's in the metadata. I will remove the word info though as it's superfluous.

**Comment by richardhallett** [comment]
@kjgarza Thanks
1. Interesting idea, I guess because dois can be resolved in different ways and the actual link to service is a DOI I didnt see need to copy the full URL.
2. This is a problem with the way filters in general work, you need to know all the filters ahead of time to avoid the strange collapsing that can occur, I think its more noticable when you have less data, hopefully with more services being added this will be clearer.

**Comment by richardhallett** [comment]
I made some further changes based on the above feedback, this is now live on https://pidservices.org
