### ISSUE TITLE
Support ORCID Search & Link claiming in DataCite Commons

### ISSUE THREAD

**Issue by sarala** [datacite/datacite#1175]
To create Tech Specification based on files in:

https://github.com/datacite/tasks/tree/master/product_specifications/10_xromv_e

**Comment by sarala** [comment]
Link to feature: https://datacite.productboard.com/feature-board/planning/features/6508447

**Comment by kjgarza** [comment]
Linking to an existing open EPIC instead of creating a new one datacite/akita#122

**Comment by richardhallett** [comment]
This is now available for preview in staging, please login with your account at:
https://commons.stage.datacite.org

The UX for this has changed slightly to the original product design due to limitations/experience with how the state of claims is managed within our system. While it might be possible to reflect it as a "single status" with a button, I think this actually is more confusing for a user and this implementation is much simpler to manage from a technical point of view as well.

Claimed:
![image.png](https://images.zenhubusercontent.com/5c8ec2f6d76ef51f6b0fd30a/1475203b-96d0-48f9-9fa4-d780cfb7825a)

Waiting for backend claiming process
![image.png](https://images.zenhubusercontent.com/5c8ec2f6d76ef51f6b0fd30a/dae30de4-d3a0-4afc-b92d-9bc3b4b1678a)

Deleted
![image.png](https://images.zenhubusercontent.com/5c8ec2f6d76ef51f6b0fd30a/75ddef5d-8578-43df-8890-a9fdc0f46367)

**Comment by mfenner** [comment]
@richardhallett This looks great in very preliminary testing! One small issue: the personal navigation menu in stage should point to the ORCID sandbox and not production ORCID record.

**Comment by mjbuys** [comment]
@richardhallett thanks for getting this ready. There are two items that I noticed:

**Comment by richardhallett** [comment]
Feedback addressed and updated to staging.
The error feedback will be rendered out as well, these messages could possible be improving, but they are part of the backend orcid integration and so direct from orcid. A future improvement (outside scope of this work) would be to improve the orcid integration to look at friendlier messages.

![image.png](https://images.zenhubusercontent.com/5c8ec2f6d76ef51f6b0fd30a/a01465fd-9e8d-48ce-8448-5e9cf60640a6)

In regard to active search and link and documentation, I will leave this to be handled and coordinated by @kjgarza as part of the Validation phase and definition of done. 

@kjgarza Do you want to review this and provide feedback on the development side? if there are additional problems.

**Comment by kjgarza** [comment]
thanks @richardhallett  I'll take over from here. I'll move this to the next stage of the [dev-journey ](https://datacite.atlassian.net/wiki/spaces/DAT/pages/2220687361/Product+Development+Journey) and start the validation process from here. I'll reach back 👍 on a github issue.

**Comment by richardhallett** [comment]
Note this has changed to be deployed under a feature flag to avoid confusion.
use ?features=orcidclaiming to activate.

**Comment by richardhallett** [comment]
This was deployed to production, closing as the work is done from a development point of view. There may be additional changes that can be addressed as individual tickets.

**Comment by kjgarza** [comment]
@richardhallett  not yet, we need to prepare the docs and close the engagement items from https://github.com/datacite/tasks/issues/86 Before we release this
