### ISSUE TITLE
Evaluate Zoho Desk

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#120]
- [ ] Labels
- [ ] conversations over emails
- [ ] inbox segregation
- [ ] rules
- [ ] integration with ZohoCRM

**Comment by mfenner** [comment]
Now that is interesting.

**Comment by mfenner** [comment]
Now that is interesting.

**Comment by mfenner** [comment]
We can reply via email.

**Comment by mfenner** [comment]
Testing support email.

**Comment by mfenner** [comment]
Testing support email.

**Comment by mfenner** [comment]
Testing support email.

**Comment by datacite-support** [comment]
very nice.


—
Martin Fenner
DataCite Technical Director
http://orcid.org/0000-0003-1419-2405

--- original message ---
On Fri, Jun 23, 2017 at 12:25 am, <notifications@github.com> Martin Fenner wrote:


Testing support email.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by datacite-support** [comment]
Another test.

**Comment by kjgarza** [comment]
Good night support email

Am 23.06.2017 00:27 schrieb "datacite-support" <notifications@github.com>:
