### ISSUE TITLE
Examine implementation of the schemeURI to valueURI relationship between the XML metadata and the Form 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1287]
#### Expected Behaviour

the value URI and the schemeURI fields contain distinct metadata and are not considered to be the same, or that one is necessarily derived from the other

#### Current Behaviour

Currently the form uses the valueURI to populate the schemeURI field when a DOI is created via the File Upload. And when a DOI is created using the Form  (including the subjects field), the schemeURI in the xml makes the assumption that "schemeURI" is the base URL of the "value URI"

#### Steps to Reproduce

example 1

DOI https://doi.test.datacite.org/dois/10.17596%2F75b8-e526 created via File Upload with the following xml:
XML:

 ```
<subjects>
        <subject subjectScheme="UAT" schemeURI="http://astrothesaurus.org/" valueURI="http://astrothesaurus.org/uat/280">Comets</subject>
    </subjects>
 ```

Form

<img width="1398" alt="Screen Shot 2021-06-17 at 16 30 14" src="https://user-images.githubusercontent.com/44582654/122416943-6e201e80-cf89-11eb-8fee-30e0bd47a2f0.png">

Example 2
DOI https://doi.test.datacite.org/dois/10.17596%2F1xv7-zr59 created via the Form, including the valueURI http://astrothesaurus.org/uat/280 in the schemeURI field. 

<img width="1112" alt="Screen Shot 2021-06-18 at 11 17 39" src="https://user-images.githubusercontent.com/44582654/122539437-e76e4e80-d027-11eb-915f-ea42c8d920f6.png">

In the resulting XML the schemeURI is considered to be the base URI of the valueURI
 ```
<subjects>
        <subject subjectScheme="UAT" schemeURI="http://astrothesaurus.org/uat" valueURI="http://astrothesaurus.org/uat/280">Comet</subject>
    </subjects>
 ```

### Context (Environment)

Fabrica

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2oifp)

**Comment by acraugh** [comment]
Just want to emphasize: Note that I entered a value URI in the Fabrica box labeled "Subject Scheme URI", and the URI was saved as entered into the _valueURI_ element, not the _schemeURI_ element.

**Comment by richardhallett** [comment]
I think maybe the behaviour here has slightly altered over last couple of years and now isn't a bug as such more a lack of scope for the Form. It currently only supports setting the valueURI via the file upload.

Ideally also you shouldnt be mixing two workflows for metadata creation.

So if you use the form and enter a value it will only set the schemeURI not the valueURI.

I'd suggest that if we are to expand the form to support valueURI as an option then it needs to be handled as a feature request.

**Comment by KellyStathis** [comment]
@richardhallett I think there is still a bug here. When updating metadata that has a valueURI, the Fabrica form is pulling the valueURI attribute into the "Subject Scheme URI" field.

XML:
<img width="1062" alt="Screen Shot 2023-05-05 at 16 05 25" src="https://user-images.githubusercontent.com/17298577/236582802-4fbf423d-0275-44dd-8840-1a6a5b60cd4d.png">

How this shows in Fabrica form:
<img width="1047" alt="Screen Shot 2023-05-05 at 16 05 39" src="https://user-images.githubusercontent.com/17298577/236582814-eee00ef4-c5b7-42d2-be7b-92d5c74f8704.png">

Since the form doesn't support Subject valueURI, it shouldn't be reading the valueURI at all and displaying that as "Subject Scheme URI" to the user.

**Comment by KellyStathis** [comment]
As an example of unexpected behaviour resulting from this, a user was unable to change the DOI state from Draft -> Findable via the form for a DOI that had valid XML. See: https://app.frontapp.com/open/cnv_apqzsnp?key=1oQ8RRzxsDJcTGpnRJeEPX1Xmx8yQvdP

Yes, the valueURI in this example should really be classificationCode, but it is technically valid XML since the xs:uri type doesn't actually verify URIs. It looks like the Fabrica form has stricter validation.

**Comment by richardhallett** [comment]
I don't think changing the state on form instead of the file upload is a valid workflow when this was created via XML and not the form.
The validation on that form field is looking for a valid URL, the form is a nicer view over the schema, the raw schema validation is better handled via file upload if you want to just follow that, but the form is trying to help you and validate this as a complete valid URL.
So while the XML is valid using the form is trying to be more helpful and go "but it really should be a url"
The problem with the form we've always had it is meant to be "smart" but it causes a few edge cases, it really needs a bit more thought.

The only bug that I might concede is the valueURI appearing in this form field, it is a bit confusing, I have a feeling that maybe it was intended just to have one field and we'd work out the schemeURI and valueURI.

So I'll look to change this to just always get the schemeURI instead.

**Comment by KellyStathis** [comment]
thanks @richardhallett! I agree with you about that part being the bug - thanks for the fix!

re: going back and forth between XML/file upload and form - this is something we do sometimes advise users to do in cases where the form doesn't support everything they want to do (e.g. adding additional subjects, or including valueURI). I realize changing state isn't one of these, but I can see where someone would expect to be able to just make a quick change like that via the form.

@MaryHirsch for cases where using XML is necessary, when you encounter these on the support desk, it might be worth submitting these to Productboard as feature suggestions to extend the Fabrica form. Since it sounds like we're trying to minimize the amount that users switch back and forth between the two methods, it would be good to flag the areas where this is happening most often, that we know of.

**Comment by richardhallett** [comment]
I think it was more about the state changes, I think it's fine to extend metadata with the file upload, but then going back to form which doesnt support the missing piece is probably not right.
So Form -> File Upload is fine
but File Upload to Form is probably a bit iffy if using things the form doesn't support.
