### ISSUE TITLE
Sitemaps not being exposed

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#1328]
Sitemaps do not appear to be exposed on DataCite commons, either staging or Live
i.e. https://commons.stage.datacite.org/sitemaps/sitemap.xml.gz

They do appear to be generated within the S3 bucket though.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2vlcl)

**Comment by KellyStathis** [comment]
This is impacting our indexing in Google Dataset Search. In Google Search Console, it looks like sitemaps for Search and Commons haven't been successfully fetched since November 2020: https://search.google.com/u/1/search-console/sitemaps?resource_id=sc-domain%3Adatacite.org

Front conversation from 2019 with context re: what we submit for Google Dataset Search: https://app.frontapp.com/open/cnv_1g6e6pv

Google's documentation: https://developers.google.com/search/docs/appearance/structured-data/dataset#sitemap

**Comment by KellyStathis** [comment]
Related, just got this indexing report from Google search console: https://app.frontapp.com/open/cnv_ajl768l

Top issues:

- Soft 404
- Duplicate without user-selected canonical
- Not found (404)
- Page with redirect
- Server error (5xx)

This is an interesting set of URLs and I'm not sure how Google is coming up with these, but I think fixing the sitemap should help.

**Comment by richardhallett** [comment]
This is now fixed.

The solution was to use Vercel proxy rewrites and I have done this to redirect to the S3 bucket where sitemaps are generated.

**Comment by KellyStathis** [comment]
Amazing, thanks @richardhallett ! I'll look at the google dataset search side now.
