### ISSUE TITLE
Improve error message from json api

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1334]
When the contributorType is missing the error is:
{"errors":[{"source":"contributors","uid":"10.22019/45ng-sk94","title":"Contributor type  is not supported in schema 4."}]}

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2okph)

**Comment by richardhallett** [comment]
If you look at the original error message in Front ticket, I think this is actually saying
"Contributor Type <blank> is not supported in schema 4" because there is a little space in between type and is.

So the error sort of makes sense but agreed it's not an overly helpful message.

Ideally this would be improved to check if it was missing entirely and say something like

"Contribute type can not be blank and is required for schema 4"

**Comment by richardhallett** [comment]
This is a feature request and looks to be tracked elsewhere.
Closing as wont fix.
