### ISSUE TITLE
DOI record generates errors 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1341]
#### Expected Behaviour

A DOI record can be opened and modified in Fabrica regardless as to how it was created and is indexed correctly

#### Current Behaviour

DOI created via the REST API generates errors

#### Steps to Reproduce

Examples:
 this DOI exists, but something in the metadata is causing the it not to be indexed when clicking on this link:https://doi.test.datacite.org/dois/10.80056%2F21020013. Updating the record fixes this, but the users need to know what is causing the issue as they will be creating large numbers of DOIs.

Modifying the record via the file upload generates and error but no errors appear in the Form

### Context (Environment)

Fabrica

**Comment by richardhallett** [comment]
The data is correctly indexed, the problem is actually to do with how we serialize "titles" titles should always be returned in json as an array of objects, so even if it was supplied as an object it should be serialized back as an array.
This is due to some inconsistencies with how the REST API was originally put together.
The error manifest itself in Fabrica due to the fact Fabrica is expecting an array therefore it causes the problem.

I will put a fix in for this, but the workaround for any user encountering this is to ensure they send title data as an array of objects, i.e.

```
"titles": [{
                "title": "test title"
            }],
```

instead of

```
"titles": {
                "title": "test title"
            },

```

**Comment by svogt0511** [comment]
Makes sense.  Seems to happen a lot in Fabrica.
