### ISSUE TITLE
UTF-8 a Characters not displaying correctly in Fabrica

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1348]
#### Expected Behaviour

metadata submitted to MDS via REST API with Content-Type: application/xml;charset=UTF-8 and displays characters correctly

#### Current Behaviour

metadata submitted to MDS via REST API with Content-Type: application/xml;charset=UTF-8 and does not display characters correctly

#### Steps to Reproduce

1. Go to https://doi.datacite.org/dois/10.18720%2Fspbpu%2F3%2F2021%2Fvr%2Fvr21-1799

It seems that problem affects records created or updated after June 11, 2021, 

### Context (Environment)

Production

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2omad)

**Comment by richardhallett** [comment]
I do not think this is a bug in Fabrica, I think the problem is with the submitted data, but this ticket is now over 2 years old and so may or may not be relevant.

I think it's difficult for us to do anything with this at this point without further information. Ideally an original metadata document that we can test against.
