### ISSUE TITLE
Review case sensitive DOI search in commons

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1354]
**Is your feature request related to a problem? Please describe.**

This works: doi:10.48714/6WT8-TV71
https://commons.datacite.org/doi.org?query=doi%3A10.48714%2F6WT8-TV71

This does NOT work: doi:10.48714/6wt8-tv71 
https://commons.datacite.org/doi.org?query=doi%3A10.48714%2F6wt8-tv71

This is not intuitive for users.

**Describe the solution you'd like**

Search for a DOI without case sensitivity

**Describe alternatives you've considered**

**Additional context**

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2on11)

**Comment by zerothi** [comment]
This is really needed. The DOI is by definition case insensitive. So search follow such a rule when specifying field searches.

**Comment by zerothi** [comment]
This should not be closed, DOIs are per definition case insensitive, so a search for a doi makes no sense in case sensitive mode.

**Comment by richardhallett** [comment]
This is an old issue but it deserves some kind of answer before closing.

Firstly I'll update the examples for reference as that DOI doesn't work, here is another from same repository:
https://commons.datacite.org/doi.org/10.48714/dtu.hpc.0001

The problem is trying to search by the doi here via doi:<doi> is going to send this as a query parameter directly through to the search index, however the doi is stored as a type "keyword" which allows for fast lookup but is also case sensitive and is stored uppercase.

The interface instead should be to go via our APIs and/or just search without a direct query, this allows us to parse the DOI and ensure we ignore case.

Either of the following will find the DOI in question, regardless of case:
https://commons.datacite.org/?query=10.48714%2Fdtu.hpc.0001
or
https://commons.datacite.org/?query=10.48714%2FDTU.HPC.0001

Or of course if the DOI is known you can go directly to the commons page:
https://commons.datacite.org/doi.org/10.48714/dtu.hpc.0001
https://commons.datacite.org/doi.org/10.48714/DTU.HPC.0001

I am closing as won't fix as it's not something we can handle without breaking our ability to do fast lookups in our search index.

Longer term if there is desire to make a more attributed based search this would need to be considered as part of product vision for Commons.
