### ISSUE TITLE
Citation formats not being generated for DataCite DOIs 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1421]
#### Expected Behaviour

Citation format generates citation in requested format for all findable DataCite DOIs

#### Current Behaviour

Both the Citation formatter and crosscite generates an error, seemingly for all DataCite DOIs

<img width="512" alt="Screen Shot 2022-01-04 at 16 22 26" src="https://user-images.githubusercontent.com/44582654/148090551-57473e1f-91a6-47c8-9418-3a0471a72b47.png">

#### Steps to Reproduce

Examples:
curl -LH "Accept: text/x-bibliography; style=apa" https://doi.org/10.15480/882.3260 is not working (with different error messages)

curl -LH "Accept: text/x-bibliography; style=apa" https://doi.org/10.5524/100005 is not working

curl -LH "Accept: text/x-bibliography; style=apa" https://doi.org/10.1126/science.169.3946.635 is working

also here: https://citation.crosscite.org/ 

### Context (Environment)

Production

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2puz9)

**Comment by svogt0511** [comment]
Just a note.  I just came across this bug report.  Another report was in my Front inbox and so I spent a little time on it. I tested this a little bit today and it seems to work intermittently.  Some 504 errors, some 404 'metadata not found' and then mysteriously seems to work.

**Comment by hvwaldow** [comment]
This problem is breaking our publication workflow since quite a while now. As a workaround we retrieve the formatted citations now from the DataCite API like so:  

    curl -LH "Accept: text/x-bibliography" https://api.datacite.org/dois/10.5524/100005?style=american-geophysical-union

**Comment by ioannistsanaktsidis** [comment]
Same here, this problem is breaking our production workflow. Is there an estimation when it is going to be fixed ? Thank you!

**Comment by richardhallett** [comment]
This is an unfortunate on-going issue related to our Content Negotiation service that has been hit with very high load, we're still investigating what we can do to accommodate, but it has a knock on effect to the citation formatter.

It'd be good to understand for future reference how this is used as part of your publication workflows?

And yes a workaround is to use the API directly to get the citation format.

**Comment by hvwaldow** [comment]
> It'd be good to understand for future reference how this is used as part of your publication workflows?

We need a citation snippet to show in the repo are too lazy to generate that ourselves.

> And yes a workaround is to use the API directly to get the citation format.

No drawback to that except that it seems we can't use it to provide things like CSL, Citeproc or DataCite-XML formatting. But I am not entirely sure about that, because that feature of the `dois`-endoint of the API doesn't seem to be documented.

**Comment by hvwaldow** [comment]
Turns out we are more impacted than previously thought, because we now would have to make our code distinguish between DOIs referring to papers and those issued by DataCite to get a citation.

A speedy estimate of when this is issue is planned to be fixed, if it is going to be fixed, would be very helpful to plan our schedule.

**Comment by richardhallett** [comment]
As an update we've made some changes to try and handle the load better please see status page for updates
https://manage.statuspage.io/pages/nmtzsv0smzk5/incidents/k7rjjq59kpyb#update

This in turn should help out any requests for the citation formatter and resolving DataCite dois.

**Comment by richardhallett** [comment]
An update on this issue.

The Citation Formatter https://citation.crosscite.org is now working for all DOIs again, this was being prevented due to the related issue around the load we saw over the last few weeks and restrictions when working with externals RAS.

In addition going via Content negotiation through https://doi.org should work too, and will take you to either DataCite Content Negotiation or the respective RA's i.e. Crossref
