### ISSUE TITLE
Authenticating with member API pulls draft DOIs from all repositories

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1448]
**Is your feature request related to a problem? Please describe.**

When a user harvests metadata with the member API using authentication they are able to retrieve Draft DOIs from other member organizations (not just their own)

**Describe the solution you'd like**

Draft DOIs are private and only visible to the member the registered them

**Describe alternatives you've considered**

**Additional context**

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2r845)

**Comment by acraugh** [comment]
@richardhallett, I was just checking on status for this. Note this is _not_ a feature, it's a **bug** - metadata that is supposed to be private is visible to people who would not otherwise be authorized to see it. This is an ongoing problem for us, causing confusion and much heated arguing about DOI statistics in meetings where our draft DOIs have been inadvertently pulled into another repository's reporting! I am getting annoyed email about compliance from people I don't work for as a result. We are very anxious to see this resolved as soon as possible. Thanks!
