### ISSUE TITLE
DOI records in commons do not consistently show the link to the associated repository

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1462]
#### Expected Behaviour

Works appear in commons added by the same repository consistently show a link to the repository record

#### Current Behaviour

DOI records in commons do not consistently show the link to the associated repository

#### Steps to Reproduce

Example 1 - as expected

DataCite Commons entry with link to repository: https://commons.datacite.org/doi.org/10.5285/c6202511-d70b-45ae-9b72-ff30f4888f5f

<img width="1102" alt="Screenshot 2022-04-01 at 14 36 52" src="https://user-images.githubusercontent.com/44582654/161274472-e6697fb7-7060-480f-86b7-9c82550b9a5a.png">

JSON includes

"container": {},

Example 2 - missing the link

Link to repo missing: https://commons.datacite.org/doi.org/10.5285/bf6d6c31-e5ad-49c3-b5e3-d6f2f092b910
<img width="1086" alt="Screenshot 2022-04-01 at 14 39 53" src="https://user-images.githubusercontent.com/44582654/161274948-a6a852b2-9f1b-4522-83e7-37f6af22beba.png">

JSON includes:

  "container": {
    "type": "DataRepository",
    "identifier": "https://www.changing-arctic-ocean.ac.uk/project/eispac/",
    "identifierType": "URL"
  },

It's not clear where this difference is coming from.

### Context (Environment)

Commons production.

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2suqd)

**Comment by jrhoads** [comment]
The difference between these two items, is the first does not have a container.Identifier in its metadata.  So it defaults to the repository in datacite with which it was registered.

The second has a container.identifier in its metadata so there is actually a link.  But there is not a container.title in the metadata which usually is the text of the link.  In this case, since the text is missing, it looks like the link is missing.
