### ISSUE TITLE
Commons shows inconsistent repository name in results

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#1490]
### Describe the bug
The repository name sometimes displays incorrectly on first load. Upon refresh, it updates to the correct repository name.

#### Expected Behaviour
The repository name should display correctly on initial page load.

#### Current Behaviour
A different repository name displays on the initial page load.

#### Steps to Reproduce
1. Go to https://commons.datacite.org/doi.org?query=wer+gewinnt+wer+verliert
2. Click result: Wer gewinnt? Wer verliert? showing repository as "Sabine Piper"
3. On record page this shows correctly as "Bertelsmann Stiftung"
4. Hit the back button
5. Results page now also shows "Bertelsmann Stiftung"

Similar behaviour can also be achieved by toggling the filters on the results page.

### Context (Environment)
This issue is causing the repository name to display incorrectly.

#### Screenshots
Loom: https://www.loom.com/share/2a27afdedd8448f387daa94c9dd3ac04

#### Further details
n/a

#### Hypothesis
Possibly related to https://github.com/datacite/datacite/issues/1464 which also involves inconsistent display in Commons.

#### Possible Implementation
n/a

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2u045)

**Comment by kjgarza** [comment]
for the second problem in Loop (filter) I think you are looking for a different DOI (check the [loop comments](https://www.loom.com/share/2a27afdedd8448f387daa94c9dd3ac04)).

I'm not sure if this is a generalized problem (it doesn’t seem so; maybe the description of the bug needs to be changed).  

Maybe useful background info is that [Sabine was the admin of this repo](https://datacite.slack.com/archives/C082HTBD1/p1607347854000700). And all DOIs created before 2020 have "Sabine Pieper"  as repo name in the index.

**Comment by KellyStathis** [comment]
I replied to your comment on the Loop - I accidentally looked at a different DOI, but the problem occurs when comparing 10.11586/2022033 with itself also.

That is useful background, thank you! Feel free to edit the description if it is too generalized currently.

**Comment by richardhallett** [comment]
I've fixed this and this repository now has the correct name appearing for all their dois.

For background this is purely an indexing issue, the overall listing page gets this information from the related client, however this relation was not updated with the newer name. However it fixed itself by going through to the DOI because this then came from the metadata directly, this then updates the internal state of Commons which is why it appeared fixed going back in the browser.

For anyone looking at this in the future (i.e. myself), fix was: reindex the dois using a query search for the repository i.e. query=client.uid:gesis.bstift
