### ISSUE TITLE
Design & test incremental mockups of the interface

### ISSUE THREAD

**Issue by espacial** [datacite/datacite#172]
Design mockups for the new DOI Registration service. The tool will be Balsamiq. 

First step: V0
- [x] Login
- [x] View Members
- [x] Create new Member
- [x] Update Member
- [x] View Data Centers
- [x] Create new Data Center
- [x] Update Data Center
- [x] View DOIs
- [x] Create DOI
- [x] Update DOI

**Comment by kjgarza** [comment]
We should use a button to call the The “Create new DOI” action; not from a menu. Creating DOIs is the foremost and only action that affects the application MDS/Schitnzel. According to the MDS analytics is the second most clicked link of the MDS(warning: that doesn't translate to doi minting). Actually, it rivals only with "create datacentre" which is exclusive for members (~40 users). It is equivalent to the “upload button” in Youtube, the “compose” button in Gmail, and the “new issue” button in Github. Therefore it should be treated with that relevance and separated from the menus [[1]](http://uxmovement.com/buttons/when-to-use-a-button-or-link/). That includes contrasting color button and outstanding position [[2]](https://www.usertesting.com/blog/2014/12/02/color-ux-conversion-rates/). 

My suggestion is to add an action button in a contrasting color either at the top left-or-right corners below the navigation bar.

![27D5C9B6-C5CB-4ABF-BA01-CDAA041EF5C8.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5936775a17ad63001a910f29/125516c66e82c728ace21e0d46bac3be76a1da8bd9a49c16877fbdc00864013e0b25f37a3da6c7099e122f502a294bdf494a4356bcbbd671f3e57862804e0ee4d3385670c03411afb9d34ebc01ba23de49d6e5bc8b19d2f42f67b6d5db1063474f4dcbed5727a29f41c95df64be24c55a61a3362e57e2431.png)

**Comment by kjgarza** [comment]
We should avoid the use of drop-down menus for finding/creating/add users. It’s a moment of friction in the user's minds. Users move their eyes much faster than we move the mouse. When we move the mouse to a menu item, we’ve already decided to click…and then the drop down gives us more options. Moreover, drop-down menus have been classified as annoying, according to usability studies from the NN Group. Additionally, depending on how they’re programmed, can be difficult for search engines to crawl. Furthermore, is always a good to keep global navigation options out of drop-down menus on the desktop. As burying your site’s top-level categories can be detrimental to user success on any site [[1]](https://www.nngroup.com/articles/drop-down-menus/). And their use is even discouraged in The Essential Guide to User Interface Design: An Introduction to GUI Design [[3]](https://books.google.de/books?id=Q3Xp_Awu49sC&pg=PA504&dq=drop+down+menus+ui+ux+guidelines&hl=en&sa=X&redir_esc=y#v=onepage&q=drop%20down%20menus%20ui%20ux%20guidelines&f=false) page 504.

An argument to use dropdown could be saving space. However, the MDS/schnitzel has so little functionality that the use of a drop-down menu is rendered unnecessary as a space saver [[2]](https://medium.com/apegroup-texts/why-drop-down-lists-are-bad-for-the-user-experience-eeda5cbbd315). In the current mockup there are around 9 potential links in the *left navigation menu bar* (including the submenus of membership and datacentre and hidden stuff (eg. stats)). For contrast Facebook has at least 12 links in its *left navigation menu bar* and manages all without dropdown menus. The original design of the MDS has this as one of its few remarkable design choices. It simple, clean, and requires fewer clicks and navigation.

BBC is a great example of how to remove drop down from the navigation menus. they used to have a drop-down menu in sports which was terribly annoying because let's be honest who cares about Cricket.

**Comment by kjgarza** [comment]
To modify the Login flow. The current flow is:

1. landing page
2. login
3. landing page

![8C077FB6-5859-45B7-B7F6-024566E966C8.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5936775a17ad63001a910f29/125516c66e82c728ace21e0d46b0b7ca74d5a58bd9a4ea1bf104bdc07c64703e0b53857d3dd5b17cea142d24565948df494a4356bcbbd671f3e57862804e0ee4d3385670c03411afb9d34ebc01ba23de49d6e5bc8b19d2f42f67b6d5db1063474f4dcbed5727a39841c95df64be24c55a11b3165e17f2431.png)

The MDS analytics data suggest the the most visited endpoint in the whole MDS UI is the "show datasets” page (which mind you is not shown in the mockup at the moment). Therefore a workflow that allow users to get what hey want with fewer clicks would be :

1. landing page
2. login
3. Show Datasets 

I suggest the flow for creation DOI follows a similar pattern.

1. Create DOI page
2. Show Datasets (in reverse chronological order)

This way we reduce the amount of clicks users have to make to reach to the desired information.

**Comment by mfenner** [comment]
Our members page in the Profiles service has a button to create a new member, a search interface, and no menu or submenu specifically
<img width="1355" alt="bildschirmfoto 2017-07-18 um 10 35 56" src="https://user-images.githubusercontent.com/23151/28307966-0de4ce0e-6ba5-11e7-88f2-489bb15a7ae1.png">
 for dealing with members.

**Comment by mfenner** [comment]
Done.
