### ISSUE TITLE
Transfer subset of 6917 DOIs to TIB.MEDIAREP

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1737]
Old repository: TIB.UBMR
new repository: TIB.MEDIAREP
DOIs: subset of 6917

[Kopie von mediarep_MEDIENwissenschaft_dois.xlsx](https://github.com/datacite/datacite/files/10569403/Kopie.von.mediarep_MEDIENwissenschaft_dois.xlsx)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_31wph)

**Comment by codycooperross** [comment]
6909 DOIs were transferred from TIB.UBMR to TIB.MEDIAREP. The reasons for the lower total are listed below: 

1. The 6917 total included the spreadsheet header, bringing the total transfer request to 6916. 
2. The following two DOIs were duplicated in the spreadsheet: 
- 10.17192/ep2009.4.634
- 10.17192/ep2002.2.2304
3. The following five DOIs listed in the spreadsheet are not registered DOIs and otherwise do not appear in DataCite systems:
- 10.17192/ep1985.4.7404
- 10.17192/ep1986.4.7148
- 10.17192/ep1993.4.5060
- 10.17192/ep2019.3.8230
- 10.17192/ep2019.3.8231
