### ISSUE TITLE
Views and Downloads in Commons do not match Event Data totals

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#1785]
#### Expected Behaviour

The total Views and Downloads in DataCite Commons for a given repository should reflect the total Views (`unique-dataset-investigations-regular`) and Downloads (`unique-dataset-requests-regular`) across all DOIs in that repository, per https://support.datacite.org/docs/consuming#how-to-display-usage.

#### Current Behaviour

The total Views and Downloads do not match what is expected from Event Data.

#### Steps to Reproduce

Example: Figshare (figshare.ars)

- [Repository page](https://commons.datacite.org/repositories/jjgc1r8) shows 125 views and 20 downloads.
- [Event Data](https://api.datacite.org/events?prefix=10.6084&source-id=datacite-usage) shows 40 `unique-dataset-investigations-regular` (views) and 40 `unique-dataset-requests-regular` (downloads). 

Example: Mendeley (bl.mendeley)
- [Repository page](https://commons.datacite.org/repositories/dl6cz4) shows 17 views and 11 downloads.
- [Event Data]( https://api.datacite.org/events?prefix=10.17632&source-id=datacite-usage) shows 11 `unique-dataset-investigations-regular` (views) and 7 `unique-dataset-requests-regular` (downloads). 

#### Screenshots

![Screen Shot 2023-04-04 at 17 01 03](https://user-images.githubusercontent.com/17298577/229948072-48172404-04a5-4cc2-ba2f-80f1312bb0d4.png)

#### Hypothesis

Figshare's events don't appear to come from these [reports submitted figshare.ars](https://api.test.datacite.org/reports?created-by=figshare.ars). They are from https://api.datacite.org/reports/b0d64b9c-94dc-47c4-a6f5-07d0f680ae28 which was submitted by cern.zenodo.

#### Possible Implementation

n/a

**Comment by KellyStathis** [comment]
@kjgarza Could you let me know if I'm missing something here about how the Views and Downloads are calculated for Commons?

**Comment by codycooperross** [comment]
I'm fairly certain these are being reported correctly. The Event Data API facets above display the events counts rather than the view/download counts for each query. If you manually count the totals for `unique-dataset-investigations-regular` and `unique-dataset-requests-regular`, they are the same in Event Data, the REST API, and GraphQL. For example, for figshare.ars: 

`unique-dataset-requests-regular`
Event Data - 20 (sum of totals) https://api.datacite.org/events?prefix=10.6084&source-id=datacite-usage&page[size]=1000&relation-type-id=unique-dataset-requests-regular&query=total:[1%20TO%20*] 
REST API - 20 (sum of downloadCounts) https://api.datacite.org/dois?query=client_id:figshare.ars 

`unique-dataset-investigations-regular`
Event Data - 125 (sum of totals) https://api.datacite.org/events?prefix=10.6084&source-id=datacite-usage&page[size]=1000&relation-type-id=unique-dataset-investigations-regular&query=total:[1%20TO%20*] 
REST API - 125 (sum of viewCounts) https://api.datacite.org/dois?query=client_id:figshare.ars%20viewCount:[1%20TO%20*]&page[size]=1000

**Comment by KellyStathis** [comment]
Thank you @codycooperross for breaking this down! Very helpful to understand where these numbers are coming from, and glad this is not a bug.
