### ISSUE TITLE
Search for full ORCID iD in Commons generates error

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#1786]
#### Expected Behaviour

A user can search for an ORCID ID e.g. `https://orcid.org/0000-0001-6133-4045` on the People tab and get results.

#### Current Behaviour

Searching for an ORCID with a full URL produces this error: 

> An error occured.
> We are sorry, but an error has occured. This problem has been logged and support has been notified. Please try again later. If the error persists please contact support.

#### Steps to Reproduce

https://commons.datacite.org/orcid.org?query=+https%3A%2F%2Forcid.org%2F0000-0001-6133-4045
https://commons.datacite.org/orcid.org?query=https%3A%2F%2Forcid.org%2F0000-0003-3585-6733

#### Screenshots
![Screen Shot 2023-04-10 at 12 23 20](https://user-images.githubusercontent.com/17298577/230980213-e698601d-6e2e-4c10-a5b5-93bba5f39549.png)

#### Further details

appears to be different from the errors described in https://github.com/datacite/datacite/issues/1451

#### Hypothesis

n/a

#### Possible Implementation

n/a

**Comment by ashwinisukale** [comment]
Hi @KellyStathis 
Thanks for logging this issue, 
Another behaviour I noticed is,

When I tried to search using only ORCHID id, it does not give me one a result, ideally there would be only one person with that specific id here is the search https://commons.datacite.org/orcid.org?query=0000-0003-3585-6733 
Searching with specific orchid id returns many records.

Could you please confirm if this is correct search term I am using and if this issue is already logged.

**Comment by KellyStathis** [comment]
Hi @ashwinisukale, I have wondered about this too!

There is similar behavior when searching Works for an exact DOI - sometimes multiple results come up, for example https://commons.datacite.org/doi.org?query=10.14454%2F3w3z-sa82

I would expect that a single result comes up when searching for an identifier, including ORCID, DOI, and ROR. However, I'm not sure if placing the identifier in the main query string (as opposed to searching a specific field) means it is treated as a general text search in ES, possibly with fuzzy matching (I am not familiar with the specifics, just speculating). @codycooperross has a better idea of how this works and may have suggestions for how we can make this more user-centered.

**Comment by codycooperross** [comment]
Each of the Commons tabs rely on different APIs, sometimes internal and sometimes external, for querying and displaying search results. The People tab uses the external ORCID API, and I believe the query is constructed here: https://github.com/datacite/lupo/blob/e541500c92db7b46cb6544720c73de91205db838/app/models/person.rb#L71-L103 We could take a look at their documentation to see what is searched and how as well as how we could customize our query for more specific results. The Organizations tab uses the ROR API, so the same investigation applies, though with with the ROR API instead of the ORCID API. I realize 16 million results for a specific ORCID doesn't make the most intuitive sense, but it is the current expected behavior of the ORCID API and our ORCID query, so I think this is more of a feature improvement/request than an issue/bug.  

The DOIs tab queries our internal ElasticSearch index. The results behavior you describe, @KellyStathis , is expected and (at least to my mind) useful because multiple fields are queried when no specific field is specified in the query string: https://github.com/datacite/lupo/blob/e541500c92db7b46cb6544720c73de91205db838/app/models/doi/graphql_query.rb#L35-L46 At the moment, these are relatedIdentifiers, titles, creator names, creator identifiers, publisher, descriptions, and subjects. You can get an overview of where the query string appears in the REST API results because the queried field are the same: https://api.datacite.org/dois?query=10.14454/3w3z-sa82 Keep in mind that you won't see the Crossref DOIs that appear in the Commons results since only DataCite DOIs appear in REST API results.

**Comment by ashwinisukale** [comment]
Wonderful! thanks a lot for the detailed explanation.
