### ISSUE TITLE
Investigate upgrading Kibana

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#2016]
We are running Kibana 7.10.2 which was released in January 2021 and is no longer receiving bug fixes. The latest version is 8.12.0.

Upgrade guide: https://www.elastic.co/guide/en/kibana/current/upgrade.html. Note this involves first upgrading to 7.17 before upgrading to 8.12. 

Questions:
- Can we upgrade the version of Kibana to 7.17 or 8.12? I am not sure if the Kibana and ES versions have to match.
- If we can't, can we check into which distribution we have installed for 7.10? One driver for this request is that [Lens](https://www.elastic.co/guide/en/kibana/current/lens.html) would be a useful tool for us, and we do not currently have access. Lens was [made generally available in 7.10.0](https://www.elastic.co/blog/whats-new-kibana-7-10-0-kibana-lens-generally-available) but access [depends on the distribution](https://discuss.elastic.co/t/kibana-7-10-2-lens-not-showing/277362). I suspect from its absence that we're using the OSS distribution rather than Basic. I also found that Elastic [changed their licensing in 2021](https://www.elastic.co/pricing/faq/licensing), which I think means for 7.11 and later, Lens is always included - see this [comparison](https://www.elastic.co/subscriptions) which lists Lens as part of the "Free and open - Basic" tier.

**Comment by KellyStathis** [comment]
@richardhallett assigning this over to you after discussion with @sarala. After that discussion, I realized our Kibana version may be tied to the ES version so I'm not sure what's possible here.

**Comment by digitaldogsbody** [comment]
Without a bit of poking, I don't know how much control we have of the Kibana instance - I have a sneaking suspicion it might be bundled with the AWS ElasticSearch service, as the usual install methods require access to the actual machine that is running ES, which I am pretty certain we don't have.

If upgrading Kibana _is_ possible, we can go to 7.17 at the latest, which will produce a log warning. Versions 8+ will throw a fatal error as the major version number is mismatching (per https://github.com/elastic/kibana#version-compatibility-with-elasticsearch).

We cannot increase the ES version beyond what it is now, we would have to switch to OpenSearch.

I don't think that different versions existed before the license switch, so that is probably irrelevant. We will be running the version that was bundled with ES7.10 under the old OS licence + probably a few Amazon patches to enable the reporting in AWS console.

**Comment by KellyStathis** [comment]
@digitaldogsbody Thank you!

From the link you shared I do not think it is possible to upgrade Kibana to 7.17, this would be the fatal error:


Situation | Example Kibana version | Example ES version | Outcome
-- | -- | -- | --
ES minor number is older. | 7.15.1 | 7.14.2 | 🚫 Fatal error

i.e., if Elasticsearch is on 7.10 and we try to upgrade Kibana to 7.17, then ES will have an older minor version number than Kibana and Kibana will fail to run.


> I don't think that different versions existed before the license switch, so that is probably irrelevant. We will be running the version that was bundled with ES7.10 under the old OS licence + probably a few Amazon patches to enable the reporting in AWS console.

To clarify, before the license switch Lens wasn't part of the OSS distribution. I think this explains why we don't have it and confirms that we can't get it.

**Comment by digitaldogsbody** [comment]
Good spot, I had read the table the wrong way round and looked at older Kibana, newer ES.

**Comment by KellyStathis** [comment]
@richardhallett I'll leave this for you to close in case you have anything to add, though I think @digitaldogsbody covered it!

**Comment by richardhallett** [comment]
@KellyStathis What's the usecase for upgrading Kibana? aside from ensuring updates? is it preventing a workflow?

I am not sure entirely what kibana is being used for, it was originally setup for some analysis work I believe?

**Comment by selgebali** [comment]
Indeed for analysis work and since we are using it more and more, it would be good to upgrade to have the newer functions that make it easier for us, e.g. autosuggestions for search parameters, ability to edit charts in dash boards, and lens charts "smart charts".

**Comment by KellyStathis** [comment]
Yes, exactly as @selgebali described :) 

Since it does not seem possible to upgrade for now as we are locked into the 7.10 open source distro, maybe a takeaway is: when we move away from 7.10 ES on AWS, continued access to Kibana or an equivalent should be a consideration. For example, for OpenSearch we would want to evaluate OpenSearch Dashboards to ensure it meets our needs.

**Comment by richardhallett** [comment]
@selgebali @KellyStathis Hi, we will be upgrading from Elasticsearch 7.10 to AWS Opensearch (2.x). This will mean Kibana will change to Opensearch dashboards. For the most part this is the same, but as they've diverged different features maybe available or not.

Also to clarify the dashboard (kibana or os dashboard) is bundled with AWS offering, that's why we have no control over it.
First and foremost the search technology (Elasticsearch soon to be Opensearch) exist as the critical underpinning of our member facing services, commons/apis/fabrica etc, kibana was always a value added addition.

As AWS does not offer an upgrade path for Elasticsearch we are not able to continue supporting Kibana, but our upgrade to newer supported versions of search software is crucial for security and long term support.

This however does come with some downsides:
1. As you noted above, you will not get Lens - This is a commercial technology and was never opensource. It is only available for Kibana
2. There is no path for continued access to Kibana due to above reasons of it's bundled with the search.
3. New features in Kibana may or may not end up in Opensearch, after 7.x they should be considered different products, even if broadly same feature set.

But the good things are:
1. Our service is now supported with an upgrade path
2. We get the performance and security features of the new Opensearch versions.
3. New features are available, e.g. Lens equivalent perhaps: https://opensearch.org/docs/latest/dashboards/visualize/visbuilder/ 

The way to access kibana is unchanged for most part, however you will be redirected to new endpoint _/dashboards:
e.g. https://localhost:9200/_dashboards/

If you want to try this out you can now look at a new staging version (this is different to test/production) that has been upgraded to latest 2.x version. I  have also imported all of the existing kibana dashboards from Production, the data is different but gives you an idea.
Follow the steps on the wiki for kibana access but you will need to use new staging setup (see wiki)

The plan will be to upgrade test/production in the next couple of weeks, exact timing to be determined, no downtime is expected for this but production will have a maintenance window during the switch.

**Comment by jrhoads** [comment]
@richardhallett @KellyStathis @selgebali 
I think this is probably complete with the upgrade to Opensearch that was carried out earlier this year.

**Comment by richardhallett** [comment]
This is complete as Joseph Said now running latest OpenSearch
