### ISSUE TITLE
Bastion move to Fargate with SSH

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#372]
We want to be moving our EC2 instances to Fargate, but with this we will need the ability to SSH in as we will no longer be able to use docker exec to obtain a bash shell.
Investigate and implement if there is a standard way to do this and start with the bastion hosts.

**Comment by mfenner** [comment]
Keep open.

**Comment by richardhallett** [comment]
Related investigation https://github.com/datacite/datacite/issues/274

**Comment by richardhallett** [comment]
@mfenner As part of your work on ROR I believe you've now got a working example of how we should go about achieving this. Please can you document here what the proposed changes are? I can then look into how to get our Bastion working with SSH and fargate.

**Comment by mfenner** [comment]
I managed to set up SSH with the root account and a specific private key. SSH for the `app` account (our deployment account) turned out to be surprisingly tricky, so left that out for now. The same goes for fetching public SSH keys from GitHub accounts of individual users.

Working example:

* Dockerfile: https://github.com/ror-community/ror-api/blob/master/Dockerfile
* terraform deployment: https://github.com/ror-community/deployment/blob/master/ror/services/api/api.json#L49-L50

You can test SSH locally by opening up a port for SSH in `docker-compose.yml`.

**Comment by mfenner** [comment]
don't close.

**Comment by mfenner** [comment]
don't close
