### ISSUE TITLE
Increase file size limit for metadata to 10 MB

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#426]

**Comment by rvanheest** [comment]
@mfenner, I’ve been testing your changes yesterday and today on one of our test environments, using the https://mds.test.datacite.org/ service. However, our ingest still fails on the DataCite upload, particularly during ‘POST /metadata’. While we got a ‘413 - Request Entity Too Large’ before the issue was fixed, yesterday I got a ‘504 - Gateway Time-out’ and today (at 8:25 AM, Dutch time) I got a ‘500 - Internal Server Error’. Also when I tried to use the production version of DataCite yesterday, using our test account, I got the same ‘500 - Internal Server Error’.

Do you have any clue of what’s going on? A 500 error seems to point to the DataCite side of the equation, but if there is anything we need to change in our code for this to work, please let me know!
