### ISSUE TITLE
Blog search/indexing

### ISSUE THREAD

**Issue by pcruse** [datacite/datacite#460]
When searching the blog.datacite.org I don't get complete results. For example, when I search "schema" or "schema.org" I get 4 results but I don't get https://doi.org/10.5438/0000-00cc

**Comment by mfenner** [comment]
Search in the blog is currently a hack, using ruby code with a JSON file. For proper searching we should index the blog, either using the DOI index, or creating a fulltext index.

**Comment by kjgarza** [comment]
### Expected Behaviour


Blog should return all results from a specific query.


### Current Behaviour


Blog returns `some` reuslts but not all of them. 

### Steps to Reproduce



When searching the blog.datacite.org I don't get complete results. For example, when I search "schema" or "schema.org" I get 4 results but I don't get https://doi.org/10.5438/0000-00cc


### Context (Environment)






### Hypothesis


the current implementation of search makes a query to the API like so
 https://api.datacite.org/pages?page%5Bsize%5D=10&page%5Bnumber%5D=1&query=schema

The query functionality in the `pages` endpoint basically parses the JSON file containing all the blog posts.
https://github.com/datacite/spinone/blob/50da1eee29d23b2e255a9813162f4fa4acbdb8a3/app/models/page.rb#L59

if the the query parameter is not included in the description (which seems to be truckated) or title of the blog post in the json file, then is not returned.

The description doesn't not contain the query term.


### Detailed Description


Options include:

a) include more fields into the search is more comprehensive. Avoidning trunckating the description.
b) use a different API (elasticsearch) to look for search results.


### Possible Implementation

**Comment by mfenner** [comment]
I have started work on implementing this via our `/dois` REST API. First step yesterday was to put all blog posts into a `DATACITE.BLOG` client account, so that you can do https://api.datacite.org/clients/datacite.blog/dois

**Comment by kjgarza** [comment]
so we are basically going for option (b) ?

**Comment by mfenner** [comment]
Yes. Only needs some minor tweaking, e.g. to support tags.

**Comment by mfenner** [comment]
REST API now supports queries for subjects (i.e. tags): https://api.datacite.org/clients/datacite.blog/dois?subject=metadata.

**Comment by kjgarza** [comment]
I think the implementation seems very straight foward

## Possible Implementation

- [ ] replace calls from spinone `page` to lupo `/dois`. https://github.com/datacite/blog/blob/cf257e342ab6be7a85672956bfd0542fd25409f3/source/javascripts/search.js#L15
- [ ] deprecate the `pages` ednpoint from spinone
