### ISSUE TITLE
searching for author as last, first format returns different results than searching as first last format

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#468]
Currently, searching for `Fenner, Martin` returns one less search result than searching for `Martin Fenner`. Users should be able to search for a name the way they're expected to enter it when providing metadata.

**Comment by mfenner** [comment]
This is caused by `creator` metadata entered as `Martin Fenner` in one case. I have create an index field that turns all author names into `given name family name`. I could add a field with `family name, given name`, but that would basically only be needed for searches for `family name, given name` in combination with wrongly entered metadata.
