### ISSUE TITLE
Naming proposal for EventData

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#512]

**Comment by daslerr** [comment]
As discussed in the team meeting: 
- We need a name for our provision of data metrics.
- The API itself does not require a name, since it will be rolled up into the REST API. This name is for the service provision generally. 
- It's fine if the name is focused only on data metrics. It doesn't have to encompass everything that Event Data makes possible. 
- We are divorcing naming/communications from the tech that enables it.
