### ISSUE TITLE
Unable to update DOI's attributes with admin account

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#606]
Using an admin account can't update the attributes (specifically landing page details) via a PATCH request to /dois/doi

Example:
`http -a admin:password PATCH https://api.test.datacite.org/dois/10.70048/483t-8j42 < doi-update-landing-page-result.json
`
Where the metadata file is:

```
 {
  "data" : {
    "type" : "dois",
    "attributes" : {
      "landingPage" : {
          "status": 200,
          "url": "http://example.com",
          "contentType": "text/html",
          "checked": "2018-03-25 01:42:23",
          "error" : "",
          "redirectCount" : 2,
          "redirectUrls" : ["http://example.com", "https://example.com"],
          "downloadLatency" : 2000,
          "hasSchemaOrg" : true,
          "schemaOrgId" : "10.70048/0910181225",
          "dcIdentifier" : "10.70048/0910181225",
          "citationDoi" : "10.70048/0910181225",
          "bodyHasPid" : true
      }
    }
  }
}
```

**Comment by mfenner** [comment]
Changed logic so that a `client_id` is no longer needed for doi updates. This makes it easier for a `staff_admin` to update DOIs, without the need to provide the client_id.

Changed the logic so that `client_id` can only be updated in a doi transfer, with `"mode": "transfer"`. 

To create new DOIs, a `client_id` is still needed.
