### ISSUE TITLE
Repository finder: Spinner does not disappear on the results page for CADC

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#620]
Environment: https://repositoryfinder.datacite.org

To reproduce:
Search for "CADC" in repository finder under "Search re3data for a repository to upload your data"
The spinner on the results page does not disappear once the page has loaded
https://repositoryfinder.datacite.org/search?open=&pid=&query=CADC&sort=relevance&subject= 

<img width="1094" alt="screen shot 2018-12-12 at 12 30 48" src="https://user-images.githubusercontent.com/44582654/49867119-cb134a80-fe09-11e8-93e9-d64ff9025771.png">

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fzqb)

**Comment by kjgarza** [comment]
### Expected Behaviour


Sppiner should disapear after reporting results of the search.

### Current Behaviour


Spinner stays presents for this specific Item ONLY

### Steps to Reproduce



Search for "CADC" in repository finder under "Search re3data for a repository to upload your data"
The spinner on the results page does not disappear once the page has loaded
https://repositoryfinder.datacite.org/search?open=&pid=&query=CADC&sort=relevance&subject=

### Context (Environment)






### Hypothesis



### Detailed Description


### Possible Implementation

**Comment by kjgarza** [comment]
fixed: https://github.com/datacite/dackel/commit/a350766c1418e44932e8ce8a47c34df912e758fb
