### ISSUE TITLE
link checker missing item with DC.identifier tag

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#633]
The link checker appears to not be picking up DOIs in the DC.identifier tag for PANGAEA items. 

Example:
DOI - https://doi.org/10.1594/PANGAEA.800694
has meta tag `<meta name=“DC.identifier” content=“https://doi.org/10.1594/PANGAEA.800694” scheme=“DCTERMS.URI”>`
but link checker shows
![screenshot 2018-12-19 at 17 02 59](https://user-images.githubusercontent.com/3181623/50231843-fb318f00-03af-11e9-8df4-18085fd0bf96.png)

This is happening for multiple PANGAEA DOIs. I didn't check other clients.

**Comment by richardhallett** [comment]
This was sort of fixed in that the text for this wasn't quite accurate.
It is correct that pangea do indeed have a DC identifier and we have picked this up correctly.
This needs to be handled by reassessing how we handle and display this information, as this isn't a bug as such (because we do gather data), I will close instead the enhancement for the data will be tracked here:
https://github.com/datacite/datacite/issues/650
