### ISSUE TITLE
OAI-PMH Internal Testing/Review

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#854]
The new OAI-PMH test system, code project name viringo, is designed to replace our existing OAI-PMH service that runs on Java against Solr.
The new one is a Python based system built to use our API directly for fetching results.

We need to do some internal testing to ensure:

1. Does it match functionally what we have in production i.e. oai.datacite.org (old) vs oai.test.datacite.org (new) with the exception of the known differences see https://github.com/datacite/viringo/issues/24
2. Are there any additional automated tests that could be added to provide a better coverage, i.e. specific result sets that could be useful.
3. From a developer perspective can you get it running within your own development environment see: https://github.com/datacite/viringo
4. No obvious bugs.

**Comment by mfenner** [comment]
I made the following changes:

* updated readme to only explain how to run via docker
* enabled running tests via docker (by optionally installing dev packages)
* enabled auto-reloading in development (needs more testing)
* enabled automated deployment via travis and terraform
* log output is text rather than json when running in development
* migrated landing page at root level from previous version
* fixed to bugs when parsing REST API response: a) `identifiers` is None rather than empty list, b) response is None. Both are now handled properly
* suggested implementing feature from previous version via https://github.com/datacite/viringo/issues/35
