### ISSUE TITLE
Routed to Fabrica homepage after creating Consortium Organization

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#857]
In Fabrica test, after creating a Consortium Organization, the user is sometimes routed to the Fabrica homepage instead of to the settings page of the newly-created Consortium Organization. 

I am only able to reproduce this inconsistently.

**Comment by richardhallett** [comment]
Making notes of investigation so far:
I believe the problem appears to be an authentication issue related to abilities for providers (abilities/providers.js)

Namely canRead - The code has:

```return this.get('currentUser.provider_id') === this.get('model.id') || (this.get('model.memberType') === 'consortium_organization' && this.get('currentUser.provider_id') === this.get('model.consortium.id'));```

However it appears that *this.get('model.consortium.id'));* is undefined therefore making the check fail.

**Comment by richardhallett** [comment]
Progress update:
1. The route to the fabrica homepage isn't actually a route, the check that's triggering it is:
providers/show.hbs
```{{#if (can "read provider" model )}}```
This then triggers the ability canRead in abilities/provider.js

2. As far as I can tell when this check above occurs the provider model it's working on is failing to load in the "consortium" related model, which is a self referencing and is loaded on async.

Also as an aside, the code seems to show the settings page currently purely due to a mistake in the abilities/provider.js code which is trying to depend on "member.consortium.id" instead of "model.consortium.id".

**Comment by richardhallett** [comment]
Okay an update to ember-can to 2.0 seems to have fixed this, I believe it was a problem in their code at allowing the promises to propagate through as valid objects.
