### ISSUE TITLE
contacts should not be retrievable by unauthenticated users

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#866]
User reports that they were able to retrieve contact information of clients without being authenticated. Desired behavior is that only authenticated users should be able to retrieve contact information. 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1bmyr)

**Comment by richardhallett** [comment]
@daslerr Can you confirm are we talking member information (providers) or repositories (clients) And via the API as well right?

**Comment by daslerr** [comment]
The original reporter (who represented a member institution) used the API to retrieve contact information for all of their institution's repositories. I've added the original Front ticket.

**Comment by richardhallett** [comment]
I looked at this a bit closer and this is actually the same behaviour it's always had, this is client contact emails which have always been exposed, because they are meant to be for the repository, which is public information.

If this is something we want to change, I suggest it's a new feature.

Note provider/member contact information is correctly hidden behind authentication still.
