### ISSUE TITLE
Host all vue components in DataCite GitHub repos.

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#887]
They should not be hosted in personal GitHub accounts. The following repos exist, but need more work:

* datacite/spitz
* datacite/datacite-components

The same goes for https://github.com/kjgarza/kishu, which is currently forked to DataCite (not an option).

**Comment by kjgarza** [comment]
I think now all the Vue code is in datacite repos 

- https://github.com/datacite/spitz
- https://github.com/datacite/datacite-components (this was not; thanks for that 👍 )

And `datacite/kishu` is been unforked 👍 
https://github.com/datacite/kishu/commit/77e44462706517bd7438bf7cbe8e427827fcc243
With the license information has been changed and also npm emails

Are there any other specific items?

**Comment by mfenner** [comment]
I would consider renaming `spitz`, to align with the name in npm.

And are these repos set up to push to npm, so that we can for example use a cdn for `datacite-components`?

**Comment by kjgarza** [comment]
yeah all of them. 

` datacite-components` just need to change the ownership in npm. At the moment npm is in degraded status, but as soon as they are back i can do that change.

Actually having different names was intentional for the repo and the widget. The issue is that we never had had a discussion on which name was better (badge, widget, component, etc) I talked to helena and robin back in august about it and we just said to postpone the discussion until we had feedback. 

With different names, we can abstract completely the code from the actual  widget.

**Comment by mfenner** [comment]
I don't understand that.
