### ISSUE TITLE
Cursor yields HTTP 400, "search_after has 3 value(s) but sort has 2"

### ISSUE THREAD

**Issue by miku** [datacite/datacite#897]
**Describe the bug**

The [cursor mechanism](https://support.datacite.org/docs/pagination#section-cursor) works well in almost all cases.

However, occasionally the API returns HTTP 400 on a request including a `page[cursor]` parameter.

Example (cursor token might be invalid already): 

* https://api.datacite.org/dois?page%5Bsize%5D=50&page%5Bcursor%5D=MTQyMzQ2ODQwMTAwMCwxMC41Njc1L0hZV0FfMjAxNSwxXzI&query=updated%3A%5B2019-11-20T00%3A00%3A00.000Z+TO+2019-11-20T23%3A59%3A59.000Z%5D

Response text:

```json
{
  "errors": {
    "title": "search_after has 3 value(s) but sort has 2."
  }
}
```

Response headers:

```
X-Firefox-Spdy: h2
cache-control: no-cache
content-encoding: gzip
content-type: application/json; charset=utf-8
date: Wed, 04 Dec 2019 14:44:52 GMT
server: nginx/1.17.3 + Phusion Passenger 6.0.4
status: 400 Bad Request
vary: Accept-Encoding, Origin
x-anonymous-consumer: true
x-powered-by: Phusion Passenger 6.0.4
x-request-id: ce7c6c55-8cf4-46e4-80d3-20dede3ef940
x-runtime: 0.061491

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Host: api.datacite.org
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0

```

**To Reproduce**

Start to query the API using cursor mechanism, iterate over a few subsequent requests until a HTTP 400 occurs.

I wrote a [minimal example script](https://gist.github.com/miku/46b6fbdec1b6ad6b1941426e3997a934) that works (for me).

```shell
#!/bin/bash

# To reproduce, run script and wait a bit, until it stop; last line should be a
# (22) from curl.
#
# $ bash cursor400.sh
# ...
# curl: (22) The requested URL returned error: 400

set -eu -o pipefail

CURSOR=1

while true; do
	echo $CURSOR
	CURSOR=$(curl --fail -v "https://api.datacite.org/dois?page%5Bsize%5D=50&page%5Bcursor%5D=$CURSOR&query=updated%3A%5B2019-11-20T00%3A00%3A00.000Z+TO+2019-11-20T23%3A59%3A59.000Z%5D" |
		jq -r .links.next | grep -Eo '[a-zA-Z0-9_-]{36,}')
done
```

**Expected behavior**

The request should return a HTTP 200 (or HTTP 404 or maybe a HTTP 400 - but with another reason, e.g. that the cursor token expired).

**Screenshots**

![](https://i.imgur.com/sMDUom3.png)

[![asciicast](https://asciinema.org/a/uRqxS0vblThOQ1u41UjMlk2ku.svg)](https://asciinema.org/a/uRqxS0vblThOQ1u41UjMlk2ku)

**Desktop (please complete the following information):**

 - OS: Linux, Ubuntu 18.04 LTS

**Smartphone (please complete the following information):**

- vanilla curl, no special setup

**Additional context**

**Comment by mfenner** [comment]
@miku thank you for this very helpful error report. 

The `cursor` is Base64-encoded, so in your example `MTQyMzQ2ODQwMTAwMCwxMC41Njc1L0hZV0FfMjAxNSwxXzI` represents `1423468401000,10.5675/HYWA_2015,1_2`. This is a comma-separated list where the first value is the timestamp (as UNIX epoch) when the record was created, and the second value is the DOI. We need the second value, as more than one DOI might have been created at the same time (we use seconds for precision, for unrelated reasons we can't currently do milliseconds). 

You see the problem here: the DOI contains a comma. Not recommended for DOIs, but also not forbidden. When parsing this string our API thinks this is three values separated by comma, and thus the error message `"search_after has 3 value(s) but sort has 2."`

The solution is simple: split the string only by the first comma, so that the cursor always represents 2 values. I have made that change, and the fix should soon be deployed to production.

**Comment by miku** [comment]
> You see the problem here: the DOI contains a comma.

I have suspected a certain property of DOIs being a problem, just haven't got around to analyze it more in depth.

> I have made that change, and the fix should soon be deployed to production.

Wonderful, thank you!

**Comment by mfenner** [comment]
@miku this is now fixed. BTW, `page[size]` can be up to `1000`.
