### ISSUE TITLE
First download tab is not selected

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#901]
https://search.datacite.org/works/10.5061/dryad.1209:

![Bildschirmfoto 2019-12-06 um 14.40.03.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/117853e6-bb88-4c4e-bbb0-09e824670d56)

**Comment by kjgarza** [comment]
fixed in https://github.com/crosscite/doi-metadata-search/commit/89f686238058b7924e31a9066e457ba8fb70716e

However, dryad made recent updates to their DOI metadata and changed publication year of all of them 

https://api.datacite.org/dois/10.5061/DRYAD.1209/metadata

So it changed them from 2010 to 2019. I think this is an error and I have sent a message to them to confirm. This affects the display.

**Comment by kjgarza** [comment]
![image](https://user-images.githubusercontent.com/1092861/71572127-00a2d880-2ade-11ea-8a37-685ba9b9b3e9.png)

Dryad has corrected the metadata
